# Generated by Django 5.1.6 on 2026-03-13 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('image_path', models.CharField(help_text='Static asset path inside the bundled template.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('author_name', models.CharField(default='Admin', max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_path', models.CharField(help_text='Static asset path inside the bundled template.', max_length=255)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.CharField(help_text='Static asset path inside the bundled template.', max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('project_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fi flaticon-idea', max_length=120)),
                ('background_shape_path', models.CharField(default='assets/images/wpo-service/shape.png', help_text='Static asset path inside the bundled template.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Follio Studio', max_length=120)),
                ('brand_name', models.CharField(default='Follio', max_length=80)),
                ('meta_description', models.CharField(default='Creative portfolio site powered by Django.', max_length=160)),
                ('hero_pre_title', models.CharField(default="I'm", max_length=30)),
                ('hero_highlight_name', models.CharField(default='John', max_length=40)),
                ('hero_name_suffix', models.CharField(default='Smith', max_length=40)),
                ('hero_role', models.CharField(default='Freelance UI/UX Designer', max_length=120)),
                ('about_title', models.CharField(default='I create products, not just art', max_length=160)),
                ('about_description', models.TextField(default='I design memorable digital experiences for ambitious brands. This portfolio is fully editable from Django admin, so text, projects, and testimonials can all be updated without touching code.')),
                ('experience_years', models.PositiveSmallIntegerField(default=7)),
                ('office_address', models.CharField(default='25 North Street, Tashkent', max_length=255)),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254)),
                ('contact_phone', models.CharField(default='+998 90 123 45 67', max_length=40)),
                ('call_to_action_text', models.CharField(default="Let's Talk", max_length=80)),
                ('copyright_text', models.CharField(default='2026 Follio. All rights reserved.', max_length=120)),
                ('logo_image', models.CharField(default='assets/images/site-logo.png', max_length=255)),
                ('footer_logo_image', models.CharField(default='assets/images/site-logo.png', max_length=255)),
                ('favicon_image', models.CharField(default='assets/images/favicon.png', max_length=255)),
                ('hero_background_image', models.CharField(default='assets/images/slider/slide-1.jpg', help_text='Static asset path inside the bundled template.', max_length=255)),
                ('hero_shape_image', models.CharField(default='assets/images/slider/hero-shape.png', help_text='Static asset path inside the bundled template.', max_length=255)),
                ('about_image', models.CharField(default='assets/images/about/about.png', help_text='Static asset path inside the bundled template.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('percentage', models.PositiveSmallIntegerField(default=75)),
                ('accent_color', models.CharField(default='#fe3e57', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('icon_class', models.CharField(default='fa fa-link', max_length=80)),
                ('hero_icon_class', models.CharField(blank=True, max_length=80)),
                ('accent_color', models.CharField(default='#fe3e57', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=150)),
                ('quote', models.TextField()),
                ('image_path', models.CharField(help_text='Static asset path inside the bundled template.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
