# Generated by Django 5.1.6 on 2026-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_demo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='award',
            name='title_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name_ru',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name_uz',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uz',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', "O'zbek")], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='project',
            name='category_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='category_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_uz',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_ru',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_uz',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='call_to_action_text_ru',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='call_to_action_text_uz',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlight_name_ru',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlight_name_uz',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_name_suffix_ru',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_name_suffix_uz',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_pre_title_ru',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_pre_title_uz',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_role_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_role_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_uz',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_address_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_address_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_ru',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_uz',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
