# Generated by Django 5.1.6 on 2026-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_update_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image_path_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='awards/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_path_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_path_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='service',
            name='background_shape_path_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_shape_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_path_file',
            field=models.FileField(blank=True, help_text='Optional uploaded image. If empty, the static path above is used.', upload_to='testimonials/'),
        ),
    ]
