# Generated by Django 5.1.6 on 2026-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_update_site_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image_path',
            field=models.CharField(blank=True, help_text='Optional static asset path. Leave blank if you upload an image below.', max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='image_path_file',
            field=models.ImageField(blank=True, help_text='Upload an image from admin. If empty, the static path above is used.', upload_to='awards/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_path',
            field=models.CharField(blank=True, help_text='Optional static asset path. Leave blank if you upload an image below.', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_path_file',
            field=models.ImageField(blank=True, help_text='Upload an image from admin. If empty, the static path above is used.', upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, help_text='Optional static asset path. Leave blank if you upload an image below.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path_file',
            field=models.ImageField(blank=True, help_text='Upload an image from admin. If empty, the static path above is used.', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_path',
            field=models.CharField(blank=True, help_text='Optional static asset path. Leave blank if you upload an image below.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_path_file',
            field=models.ImageField(blank=True, help_text='Upload an image from admin. If empty, the static path above is used.', upload_to='testimonials/'),
        ),
    ]
